# ----------------------------------------
# Configuração do Banco de Dados (Neon.tech)
# ----------------------------------------
datasources.default.url=jdbc:postgresql://ep-spring-mud-ac3bwg3n-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
datasources.default.username=neondb_owner
datasources.default.password=npg_5cnQU9zsakIX
datasources.default.driverClassName=org.postgresql.Driver

# ----------------------------------------
# Configuração do JPA / Hibernate
# ----------------------------------------
# 'update' cria as tabelas automaticamente para os requisitos do Lab02
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
# Importante para bancos na nuvem
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Avisa onde estão as classes que vão virar tabelas no banco
jpa.default.entity-scan.packages=com.aluguel.models