# ----------------------------------------
# Configuração do Banco de Dados (Neon.tech)
# ----------------------------------------
datasources.default.url=${JDBC_URL}
datasources.default.username=${DB_USER}
datasources.default.password=${DB_PASSWORD}
datasources.default.driverClassName=org.postgresql.Driver

# ----------------------------------------
# Configuração do JPA / Hibernate
# ----------------------------------------
# 'update' cria as tabelas automaticamente para os requisitos do Lab02
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
# Importante para bancos na nuvem
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Avisa onde estão as classes que vão virar tabelas no banco
jpa.default.entity-scan.packages=com.aluguel.models

# Liga o modo detetive da segurança do Micronaut
logger.levels.io.micronaut.security=TRACE